### ISSUE TITLE
recording-with-yonet

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#1]
Date: 2016-05-31

Show notes
- 自己紹介など
- [Salesforce Summer'16 リリースノート](https://releasenotes.docs.salesforce.com/ja-jp/summer16/release-notes/salesforce_release_notes.htm)
- [SalesforceでのWebアプリケーション開発についての現状（部外者向け）](http://qiita.com/stomita/items/992f6be7084565420e8d)
- [2016/5/27 の Salesforce | SALESFORCE DEVELOPERS.INFO](http://zaki-yama.github.io/salesforce-developers.info/2016-05-27.html)
- [5/19 Tokyo Salesforce DG もくもく会 #10](http://www.meetup.com/ja-JP/Tokyo-Salesforce-Developer-Group/events/230861999/)
- [6/22 Tokyo Salesforce DG Meetup #12](http://www.meetup.com/ja-JP/Tokyo-Salesforce-Developer-Group/events/231238976/)
- [7/20-21 Salesforce Summer 2016 Tokyo](http://eventjp.salesforce.com/)

**Comment by takahiro-yonei** [comment]
タイトルの `with-nonet` って、もしかして `with-yonet` のtypoですか...？

**Comment by kuratani** [comment]
すみません、GitHubかIMEが勝手に…。修正しときました。

**Comment by kuratani** [comment]
話題から拾って更新してみました

# Show notes

## 自己紹介など
- [Tokyo Salesforce Developer Group Facebookページ](https://www.facebook.com/groups/salesforcedugjapan/)
- [Tokyo Salesforce Developer Group Meetup](http://www.meetup.com/ja-JP/Tokyo-Salesforce-Developer-Group/)

## Summer'16
- [Salesforce Summer'16 リリースノート](https://releasenotes.docs.salesforce.com/ja-jp/summer16/release-notes/salesforce_release_notes.htm)

## SALESFORCE DEVELOPERS.INFO
- [2016/5/27 の Salesforce | SALESFORCE DEVELOPERS.INFO](http://zaki-yama.github.io/salesforce-developers.info/2016-05-27.html)
- [「エンドユーザー自らシステムを構築する時代」を卓越したJS技術で現実化するマッシュマトリックスのクラウドサービス (1/3)：CodeZine（コードジン）](http://codezine.jp/article/detail/9420)
- [Salesforce.com、主力サービス基盤にAmazonクラウド活用を表明。より迅速に海外展開するため。自社データセンターへの投資も継続 － Publickey](http://www.publickey1.jp/blog/16/salesforcecomamazon.html)
- [Integrating Salesforce and Slack | Salesforce Developers](https://developer.salesforce.com/events/webinars/slackintegration)
- [Tokyo Salesforce Developer Group Slackチーム招待ページ](https://slackin-tokyosalesforcedg.herokuapp.com/)
- [jsforceを使ったSalesforce便利TIPS](http://freedom-man.com/blog/jsforce-salesforce-tips/)

## イベント
- [5/19 Tokyo Salesforce DG もくもく会 #10](http://www.meetup.com/ja-JP/Tokyo-Salesforce-Developer-Group/events/230861999/)
- [6/22 Tokyo Salesforce DG Meetup #12](http://www.meetup.com/ja-JP/Tokyo-Salesforce-Developer-Group/events/231238976/)

**Comment by kuratani** [comment]
収録終わったのでクローズします

**Comment by takahiro-yonei** [comment]
ありがとうございます。

修行して、また出直せるようガンバリマス。。
