### ISSUE TITLE
（岡本さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#10]
- AI周りのガチじゃない雑な話
  - 人はよいモデルを選べるのか？
  - AIをテストするとは？
- コミュニティの話
  - まんねり＆内輪化＆高齢化していく問題
- （レギュラーテーマ）エンジニア論

- AI関連記事
  - [How old do I look](https://how-old.net)
  - [結論しか出さない機械学習システムでは使い物にならない](https://www.technologyreview.jp/s/32595/the-u-s-military-wants-its-autonomous-machines-to-explain-themselves/)
  - [「Deep Learningをサービスに導入したい！」人が泣かないために知っておきたいこと](http://www.atmarkit.co.jp/ait/articles/1702/15/news014.html)
  - [Recurrent Neural Networkとは何か、他のニューラルネットワークと何が違うのか](http://www.atmarkit.co.jp/ait/articles/1608/26/news011.html)
  - [校正担当者必見!? 地味な誤字脱字で泣かないためのRecurrent Neural Networkのスゴイ生かし方](http://www.atmarkit.co.jp/ait/articles/1610/06/news015.html)
  - [LSTMとResidual Learningでも難しい「助詞の検出」精度を改善した探索アルゴリズムとは](http://www.atmarkit.co.jp/ait/articles/1611/11/news016.html)

**Comment by takahiro-yonei** [comment]
> まんねり＆内輪化＆高齢化していく問題

ホント、ごめんなさい... 😭
