### ISSUE TITLE
（小泉さん）収録ネタ #18

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#13]
## TrailheaDXこぼれ話

- キャンペーンについて
  - [Trailhead Superbadgeを獲得してTrailheaDXに参加しよう](https://developer.salesforce.com/events/templates/trailhead_jp_springcampaign_2017)
- SFDCの中の人について
- サンフランシスコについて
- アイアンマン

## Herokuの話
- [Heroku Connect](https://devcenter.heroku.com/articles/heroku-connect)
- [Lightning Connect](https://trailhead.salesforce.com/ja/modules/lightning_connect/units/lightning_connect_introduction)
- Customer Community、Partner Community
- [Heroku Enterprise](https://www.heroku.com/enterprise)
- [SendGrid](https://devcenter.heroku.com/articles/sendgrid)
- [NewRelic](https://elements.heroku.com/addons/newrelic)
- [Papertrail](https://elements.heroku.com/addons/papertrail)
- Herokuのサポートについて

# その他
- カンファレンスモーニング、ランチ
- わたしの考えるセールスフォースを使ったインテグレーション
  - [Heroku](https://www.heroku.com/)
  - [Force.com](https://www.salesforce.com/jp/products/platform/overview/)
  - [Service Cloud](https://www.salesforce.com/jp/products/service-cloud/overview/)
  - [Pardot](https://www.salesforce.com/jp/products/pardot/overview/) or [Eloqua](https://www.oracle.com/marketingcloud/products/marketing-automation/index.html) ?

# After Show
- [レジェンドオブトゥモロー](https://www.happyon.jp/legends-of-tomorrow)
- [シリコンバレー](https://www.happyon.jp/silicon-valley-2014)
- [マーベルスタジオ](https://ja.wikipedia.org/wiki/マーベル・スタジオ)

**Comment by niseissa** [comment]
## TrailheaDXこぼれ話
- キャンペーンについて
- SFDCの中の人について
- サンフランシスコについて
- アイアンマン
## Herokuの話
- Heroku Connect
- Lightning Connect
- Customer Community、Partner Community
- Heroku Enterprise
- SendGrid
- NewRelic
- Papertrail
- Herokuのサポートについて

**Comment by niseissa** [comment]
カンファレンスモーニング、ランチ
わたしの考えるセールスフォースを使ったインテグレーション

**Comment by niseissa** [comment]
after show 
レジェンドオブトゥモロー
シリコンバレー
マーベルスタジオ

**Comment by kuratani** [comment]
むむ…海外ドラマは見てないので詳しくないです。すみません。

**Comment by niseissa** [comment]
わたしの考えるセールスフォースを使ったインテグレーションのなかみのネタ キーワード

heroku
Force.com
ServiceCloud
Pardot or Eloqua ?

**Comment by kuratani** [comment]
https://ja.wikipedia.org/wiki/%E3%82%B8%E3%83%A7%E3%82%A8%E3%83%AB%E3%83%BB%E3%82%B9%E3%83%9D%E3%83%AB%E3%82%B9%E3%82%AD
