### ISSUE TITLE
（shunkosaさん）収録ネタ #20

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#14]
# Salesforce関係
- Trailhead Award
- [Salesforce World Tour Tokyo 2017](https://www.salesforce.com/jp/campaign/worldtour17/)
- [Dreamforce 2017](https://www.salesforce.com/dreamforce/)

# Winter '18リリース関連
- 開発系
- Service Cloud全般

# クラウド型コールセンタ関連
- [公衆電話回線網のIP網移行](http://internet.watch.impress.co.jp/docs/news/729373.html)
- [Amazon Connect](https://aws.amazon.com/jp/connect/)
- [Dialpad](https://dialpad.com/)

# その他
- [Success Community](https://success.salesforce.com/) → Trailblazer Community

**Comment by shunkosa** [comment]
# Winter '18リリース関連
- 開発系
- Service Cloud全般

# クラウド型コールセンタ関連
- [公衆電話回線網のIP網移行](http://internet.watch.impress.co.jp/docs/news/729373.html)
- [Amazon Connect](https://aws.amazon.com/jp/connect/)
- [Dialpad](https://dialpad.com/)

# その他
- Success Community
