### ISSUE TITLE
(讃岐さん、中山さん) 収録ネタ 

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#16]
# [Dreamforce](https://www.salesforce.com/dreamforce/)

## 発表

- myTrailhead
- myEinstein
- mySalesforce
- myLightning
- myIoT

## 会場

- デベロッパーゾーン
- セッションの雰囲気
- MVPパーティー
- コミュニティグループリーダー朝ごはん
- ミニハック
- 滝・洞窟

## 観光

- [セールスフォース・タワー](https://en.wikipedia.org/wiki/Salesforce_Tower)
- [カリフォルニア科学アカデミー](https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AA%E3%83%95%E3%82%A9%E3%83%AB%E3%83%8B%E3%82%A2%E7%A7%91%E5%AD%A6%E3%82%A2%E3%82%AB%E3%83%87%E3%83%9F%E3%83%BC)
- [グレース大聖堂（閉まってた）](https://ja.wikipedia.org/wiki/%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B9%E5%A4%A7%E8%81%96%E5%A0%82)

### SALESFORCE DEVELOERS.INFO

- [Dreamforce 2017 発表内容まとめ(Day 1)](https://zaki-yama.github.io/salesforce-developers.info/2017-11-07-df17-day1.html)

### TerraSkyBase

- [Dreamforce2017 day0：Dreamforceが開幕します！](https://base.terrasky.co.jp/articles/FBeIe)
- [Dreamforce2017 day1：基調講演](https://base.terrasky.co.jp/articles/Zm2nw)
- [Dreamforce2017 day2：Salesforceのセキュリティと認証の未来＆Big Objects と Async SOQLでBig Dataのチャンピオンになる](https://base.terrasky.co.jp/articles/BD1ly)
- [Dreamforce2017 day2:Marketing Cloud Keynote](https://base.terrasky.co.jp/articles/7VhKd)
- [Dreamforce2017 day2：Service Cloud Keynote](https://base.terrasky.co.jp/articles/OblmD)
- [Dreamforce2017 day2 : Developer Keynote](https://base.terrasky.co.jp/articles/2b2lB)
- [Dreamforce2017 day3：Financial Services with Salesforce '17](https://base.terrasky.co.jp/articles/fSi69)
- [Dreamforce2017 day3：Salesforce Platform Keynote](https://base.terrasky.co.jp/articles/DE2Pz)
- [Dreamforce2017 day3：フィールドサービス最新情報](https://base.terrasky.co.jp/articles/wCdE8)
- [Dreamforce2017 day4：Salesforce Roadmap](https://base.terrasky.co.jp/articles/vHHkS)
- [Dreamforce2017 day4：Einstein Insights、Einstein Analytics、Einstein Discoveryについて](https://base.terrasky.co.jp/articles/4RLfo)
- [Dreamforce2017 day 5：まとめ](https://base.terrasky.co.jp/articles/z16aP)

### セールスフォースの豆知識2.0
- [Dreamforce17にいってきます！](http://sf.flect.co.jp/entry/df17)
- [Dreamforce17-前日](http://sf.flect.co.jp/entry/df17day0)
- [Dreamforce '17 で mySalesforceが発表されました](http://sf.flect.co.jp/entry/2017/11/07/184741)
- [Dreamforce17-Day1(基調講演)](http://sf.flect.co.jp/entry/df17day1)
- [Marc BenioffのKeynote聞いてきました！](http://sf.flect.co.jp/entry/2017/11/07/190628)
- [Dreamforce17-Day2(プロダクトキーノート)](http://sf.flect.co.jp/entry/df17day2)
- [Dreamforce17-Day3(プロダクトキーノート)](http://sf.flect.co.jp/entry/df17day3)
- [Dreamforce17-Day4(本社訪問)](http://sf.flect.co.jp/entry/df17day4)
- [DreamforceのBreakout Sessionsを聞いて](http://sf.flect.co.jp/entry/2017/11/10/193418)
- [Lightning Mega Session報告+myLightningのご紹介](http://sf.flect.co.jp/entry/2017/11/15/165459)

### 鈴木貞弘の“Salesforceの匠に聞け！”
- [第33回 Dreamforce'17 直前レポート](http://blogs.itmedia.co.jp/sadahiro29/2017/11/33_dreamforce17.html)
- [第34回 Dreamforce'17 Day1レポート](http://blogs.itmedia.co.jp/sadahiro29/2017/11/34_dreamforce17_day1.html)
- [第35回 Dreamforce'17 Day2レポート](http://blogs.itmedia.co.jp/sadahiro29/2017/11/35_dreamforce17_day2.html)
- [第36回 Dreamforce'17 Day3レポート](http://blogs.itmedia.co.jp/sadahiro29/2017/11/36_dreamforce17_day3.html)
- [第37回 Dreamforce'17 Day4レポート](http://blogs.itmedia.co.jp/sadahiro29/2017/11/37_dreamforce17_day4.html)

# イベント
- 2017/12/13(水) [Salesforce Basecamp Tokyo](https://www.salesforce.com/jp/campaign/basecamp17/)

**Comment by nakayamasan** [comment]
- カリフォルニア科学アカデミー
- グレース大聖堂（閉まってた）
- MVPパーティー
- コミュニティグループリーダー朝ごはん
- ミニハック
- 滝

**Comment by nakayamasan** [comment]
![default](https://user-images.githubusercontent.com/10152942/33005347-c29301a2-ce08-11e7-919d-07a4f6c920e4.jpg)
![default](https://user-images.githubusercontent.com/10152942/33005432-21dde442-ce09-11e7-8342-60421ba952cb.jpg)
![default](https://user-images.githubusercontent.com/10152942/33005453-38cd3be4-ce09-11e7-855f-1298c2f4ac81.jpg)

写真とかグッズを持っていきます−

**Comment by isanuki** [comment]
なかやまさんねこ６匹

**Comment by isanuki** [comment]
アマンダさん
