### ISSUE TITLE
（米井さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#17]
# コミュニティネタ
* 1年をふりかえって
* 来年に向けての抱負

# ネタ
* [Lightning Platform: The Future of App Development](https://www.salesforce.com/blog/2017/11/lightning-platform-future-app-development.html)
* [Spring 18 New Features - Naveen Dhanaraj](https://naveendhanaraj.wordpress.com/2017/12/15/spring-18-new-features/)
* [5 Must See Salesforce Spring ’18 Features! - Salesforce Ben](http://www.salesforceben.com/5-must-see-salesforce-spring-18-features/)
* [Advanced Apex Specialist](https://twitter.com/takahito0508/status/941884738322579456)
* [Platform Developer試験の緊急停止](http://certification.salesforce.com/platformdeveloperI)

# イベント
* [Salesforce Basecamp Tokyo](https://www.salesforce.com/jp/campaign/basecamp17/)
* [Dreamforce 4 U](https://sfdg.tokyo/blog/2017-12-13-dreamforce4u/)
* イベント告知

**Comment by takahiro-yonei** [comment]
ネタを書こうと思ったら、既に記載いただき、ありがとうございます。

* Platform Developer試験の緊急停止
http://certification.salesforce.com/platformdeveloperI
