### ISSUE TITLE
（山﨑さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#20]

**Comment by zaki-yama** [comment]
* Advent Calendar がずいぶん昔のことのよう
  * [Salesforce Platform Advent Calendar 2017 - Qiita](https://qiita.com/advent-calendar/2017/salesforce-platform)
  * [Salesforceで技術は学べるのか？](https://blog.freedom-man.com/skillup-with-salesforce/)
* 子育てエンジニアはいかにして時間を確保しているのか
* SFDG コミュニティの今後
  * 何したい？
  * あるいは最近コミュニティに全然貢献できてない件

**Comment by kuratani** [comment]
- 大雪
- 継続的勉強会
- [Adding User Feedback to your Package](https://andyinthecloud.com/2018/01/28/adding-user-feedback-to-your-package/)
- [ReactのカスタムRendererを使ってLightningネイティブコンポーネントを開発する](https://qiita.com/stomita/items/88f7cfcf1b7261140c89)
- デブサミ
- TrailheaDX
- [採用面接ゲリラガイド(version 3.0)](http://local.joelonsoftware.com/wiki/採用面接ゲリラガイド%28version_3.0%29)
