### ISSUE TITLE
（須山さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#21]
- [Migration.fm Monthly News / March, 2018](https://blog.migration.fm/migration-fm-monthly-news-march-2018-9c6e3a1d2776)

**Comment by suyaman** [comment]
# ネタ memo
* サンフランシスコ旅行（ついでにTrailheaDX）の裏話とか
  * Uber
  * アルカトラズ、2階建てバス
  * 朝食やお土産とか
  * SWAG
  * Integration Cloud / Lightning Flow
* エンジニアの生存戦略とか
  * Architect or Developer
  * 部署異動
* AIアプリコンテストとか
  * 提出できず。
* コミュニティ活動とか
  * SFDG Tokyo
  * SFDGルーキー会
  * 新グループ
