### ISSUE TITLE
（小坂さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#22]

**Comment by shunkosa** [comment]
* Spring '18リリース
  * あまり目玉機能はないですが…
  * [Lightning Mass Quick Action](http://releasenotes.docs.salesforce.com/ja-jp/spring18/release-notes/rn_casesMQA.htm)
  * [Lightning Component in Flow](http://releasenotes.docs.salesforce.com/ja-jp/spring18/release-notes/rn_forcecom_flow.htm)
* 最近のイベントなど
  * デブサミ2018
    * おつかれさまでした！
  * [コミュニティ主体のイベント](https://trailhead.salesforce.com/en/community/events)
  * Salesforce World Tour Australia (先週)
    * [Pitchcomp](https://www.salesforce.com/au/campaign/sfwt18/pitchcomp/)
  * TrailheaDX (今月末)
    * 行けません…
  * Global Gatherings
* IdeaSpokes
  * コミュニティのアイデアを綺麗にする活動
  * [記念品](https://twitter.com/shunkosa/status/965969998316421121)
  * [@Amy Oplinger](https://twitter.com/salesforceamy) さんにお会いしました
* Partner Value ScoreにTrailheadが加わった
* 英語学習
   * [Best Salesforce Podcasts](https://player.fm/podcasts/Salesforce)
* 最近読んだ本
  * [エンジニアリング組織論への招待](https://www.amazon.co.jp/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%AA%E3%83%B3%E3%82%B0%E7%B5%84%E7%B9%94%E8%AB%96%E3%81%B8%E3%81%AE%E6%8B%9B%E5%BE%85-%E4%B8%8D%E7%A2%BA%E5%AE%9F%E6%80%A7%E3%81%AB%E5%90%91%E3%81%8D%E5%90%88%E3%81%86%E6%80%9D%E8%80%83%E3%81%A8%E7%B5%84%E7%B9%94%E3%81%AE%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0-%E5%BA%83%E6%9C%A8-%E5%A4%A7%E5%9C%B0/dp/4774196053)

**Comment by skosaka** [comment]
* 最近読んだ本
  * [エンジニアリング組織論への招待](https://www.amazon.co.jp/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%AA%E3%83%B3%E3%82%B0%E7%B5%84%E7%B9%94%E8%AB%96%E3%81%B8%E3%81%AE%E6%8B%9B%E5%BE%85-%E4%B8%8D%E7%A2%BA%E5%AE%9F%E6%80%A7%E3%81%AB%E5%90%91%E3%81%8D%E5%90%88%E3%81%86%E6%80%9D%E8%80%83%E3%81%A8%E7%B5%84%E7%B9%94%E3%81%AE%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0-%E5%BA%83%E6%9C%A8-%E5%A4%A7%E5%9C%B0/dp/4774196053)

**Comment by kuratani** [comment]
migration.fm Monthly News March, 2018 
https://blog.migration.fm/migration-fm-monthly-news-march-2018-9c6e3a1d2776
