### ISSUE TITLE
（ロボホンズさん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#26]
- AIアプリコンテストでGrand Prize

**Comment by nmin000** [comment]
- メンバー自己紹介
- 優勝したアプリについてご紹介
https://devpost.com/software/ai-album
　　-AIアプリコンテスト最終選考の裏話（最終選考でうまく伝えられなかったことをここでリベンジ！）
　　　　-ロボットであることの魅力
　　　　-質疑応答でうまく答えられなかったところの回答
- ブログ紹介
http://niimin.hateblo.jp/

なんだか、私一人で8割しゃべってしまいそうなので、他のメンバーがしゃべるネタ考えます。。。
