### ISSUE TITLE
（田実さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#27]

**Comment by tzmfreedom** [comment]
* 昨今の乃木坂について
* 今のお仕事の話とか少々
* [Salesforceで技術は学べるのか？](https://blog.freedom-man.com/skillup-with-salesforce/)
* [[Salesforce] Apexのローカル実行環境を作ろうとしている話](https://blog.freedom-man.com/salesforce-apex-local/)
* [SalesforceのワークフロールールをApexトリガに変換するヤーツ作った](https://blog.freedom-man.com/salesforce2apex/)
  * https://github.com/tzmfreedom/salesforce-formula-parser
* AIハッカソン、ボロ負けだった話
  * https://github.com/tzmfreedom/salesforce-einstein
* Salesforce実装アンチパターンの電子書籍を書いている話
  * https://github.com/tzmfreedom/yasd
* 技術力評価会の話とか…？

**Comment by kuratani** [comment]
今回はこちらからのネタはなしで大丈夫ですね〜
