### ISSUE TITLE
（小坂さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#28]
* CTA
* インド

**Comment by shunkosa** [comment]
- CTA
  -  レビューボードの話
  - [CTA Prep 2min Drill - Joe Castro](https://www.youtube.com/channel/UCZKe04P95Ze_dkwVHdmuvSA/videos)
  - [Ladies be Architects](https://archladies.com/)
  - [Trailmix : 【SFDC公式】アーキテクトジャーニー：認定テクニカルアーキテクト](https://trailhead.salesforce.com/ja/users/00550000007Z206AAC/trailmixes/architect-trailmix-master-ja)
  - [Salesforce 認定 B2C Commerce Technical Solution デザイナー](http://tandc.salesforce.com/credentials)
- インド
  - [India Dreamin' 18](http://www.indiadreamin.in/)
  - [My IndiaDreamin18 Highlights](https://shunkosa.github.io/posts/my-indiadreamin18-highlights/)
  - 交通とか食事とか
- コミュニティ関連いろいろ
  - [もう勉強会には行かないと思う](https://anond.hatelabo.jp/20181012090959)
  - [Learn About the Salesforce MVP Nomination Process (Plus How to Nominate for 2019!)](https://www.salesforce.com/blog/2018/11/salesforce-MVP-nominations-2019)
  - Renewal Feedback
  - Japan Dreamin'
- World Tour Tokyo 2018
  - [ハイライトトップ10](https://www.salesforce.com/jp/blog/2018/12/worldtour-tokyo-2018-top10-highlights.html)
  - ミニハック
- Spring '19 Release
  - [リリースノート](https://releasenotes.docs.salesforce.com/en-us/spring19/release-notes/salesforce_release_notes.htm)
  - [ストレージ容量増えた](https://releasenotes.docs.salesforce.com/en-us/spring19/release-notes/rn_storage.htm?edition=&impact=)
  - [この項目ってどこで使われてる？](https://releasenotes.docs.salesforce.com/en-us/winter19/release-notes/rn_forcecom_fields_where.htm)
  - LWC
    - [LWC Quick Overview](https://www.wissel.net/blog/2018/12/lwc-quick-overview.html)
    - [trailheadapps/lwc-recipe](https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc)
- Advent Calendarふりかえり
  - [Trailblazer Advent Calendar 2018](https://adventar.org/calendars/3195)
  - [Salesforce Platform Advent Calendar 2018](https://qiita.com/advent-calendar/2018/salesforce-platform)

**Comment by shunkosa** [comment]
* LWC
