### ISSUE TITLE
（米井さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#29]
2018年のふりかえり
- [Lightning Platform Meetup(2018/01/16)](https://sfdg.tokyo/blog/2018-01-16-Lightning-Platform-Meetup/)
- [Developers Summit 2018(2018/02/15)](https://sfdg.tokyo/blog/2018-02-15-DevSumi/)
- [Salesforce Developers Meetup #17(2018/03/01)](https://sfdg.tokyo/blog/2018-03-01-salesforce-developers-meetup-17/)
- [Salesforce MVPs 2018](https://sfdg.tokyo/blog/2018-03-15-salesforce-mvps-2018/)
- [Community Talk @JAWS DAYS 2018(2018/03/10)](https://sfdg.tokyo/blog/2018-03-21-jaws-days-2018/)
- [TrailheaDX(1日目)(2018/03/28)](https://sfdg.tokyo/blog/2018-03-28-TrailheaDX-1st-day/)
- [TrailheaDX(2日目)(2018/03/29)](https://sfdg.tokyo/blog/2018-03-29-TrailheaDX-2nd-day/)
- [TrailheaDX 2018 Global Gatherings in Tokyo(2018/04/25)](https://sfdg.tokyo/blog/2018-04-28-TDX18GG-Tokyo/)
- [Salesforce Developers Meetup #18 開催レポート(2018/06/28)](https://sfdg.tokyo/blog/2018-06-28-salesforce-developers-meetup-18/)
- [DF18 Global Gathering, Tokyo 開催レポート(2018/10/10)](https://sfdg.tokyo/blog/2018-10-10-dreamforce-global-gathering-2018/)
- [Salesforce Developers Meetup #19 開催レポート(2018/10/30)](https://sfdg.tokyo/blog/2018-10-30-salesforce-developers-meetup-19/)
- [India Dreamin 2018 に小坂さんが登壇しました！](https://sfdg.tokyo/blog/2018-12-02-india-dreamin18/)
- Salesforce World Tour Tokyo 2018

# Advent Calendar 2018
- [Salesforce Platform Advent Calendar 2018](https://qiita.com/advent-calendar/2018/salesforce-platform)
- [Trailblazer Advent Calendar 2018](https://adventar.org/calendars/3195)

**Comment by takahiro-yonei** [comment]
（自分のツィートより）

### 1月

* https://twitter.com/yonet77/status/949945242169499648
    * サヨナラ、とは？
* https://twitter.com/i_sanuki/status/950640501086150656
    * 徹底討論
* https://twitter.com/SalesforceDevJP/status/952498614483365888
    * 満員早すぎ

### 2月

* https://twitter.com/yonet77/status/964778096418148353
    * Trailheadもくもく会があちらこちらで
* https://twitter.com/niseissa/status/971907807455854594
    * DevSumiの徹底討論

### 3月

* https://twitter.com/salesforce/status/974300451544985600
* https://twitter.com/salesforce/status/974300199014289408
* https://twitter.com/salesforce/status/974299946848542720
    * MVPラッシュ
* https://twitter.com/yonet77/status/974507805985001473
    * React-Lightning 分科会（もっと増やしたいね）
* https://twitter.com/MuleSoft/status/976210929154076672
    * MuleSoft が Salesforce ファミリーに
* https://twitter.com/yonet77/status/978797334044684288
    * TrailheaDX 疲れた
* https://twitter.com/thisisnagano/status/979903040764362752
    * Heroku JPサイト立ち上がれ

### 4月

* https://twitter.com/takahito0508/status/982500225901215744
    * Salesforce Saturday 始動

### 6月

* https://twitter.com/a_kuratani/status/1005055781652140034
    * AIアプリコンテスト
* https://twitter.com/i_sanuki/status/1009449295966138368
* https://twitter.com/yonet77/status/1009820262739505152
    * F越さんロス...

### 9月 (DF で賑わう)

* https://twitter.com/i_sanuki/status/1035386947097702400
    * DFにいけない俺らは...

### 10月

* https://twitter.com/nana8_admin/status/1046917423033540608
    * Trailhead Quest こうやってまた煽る...
* https://twitter.com/yonet77/status/1049964905460248576
    * global gathering...
* Meetupもやったっけ。

### 12月

* Advent Calendar くらいか。

**Comment by takahiro-yonei** [comment]
（番外）

「APIマネジメントは死んだ」。サービスメッシュ、IstioとKongの進む道
http://www.atmarkit.co.jp/ait/articles/1810/26/news033.html

salesforceだとむずかしそうな。
