### ISSUE TITLE
（横山さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#36]

**Comment by takahiro-yonei** [comment]
* 最近何してますか？
* CTAになると、どんないいことがあるのか？
    * ヘッドハンティングが毎週のようにくるとかー　年収がー　ステキな会合に招待されるとかー
* 横山さんが、salesforceと付き合い始めてから、現在に至るまでの変化はどう感じてる？
    * さらには今後salesforceはどう変化していく（あるいはどう変化していって欲しい？）と考えてるか？
* 仕事以外でハマってるものとか

**Comment by takahiro-yonei** [comment]
（脱線メモ）
[コレ](https://qiita.com/bitai/items/c8941da683ebedd135fd#4%E4%BD%8Dapex) は本当だろうか...？

---
> ### 4位 Apex
> SalseForceのプログラミング言語です。ApexはJavaに似ており、Java言語ユーザには親しみのある記述方法を提供しています。Salesforceは開発者に高いインセンティブを支払うことで有名であり、中小ベンダーにとって採用の敷居が低い人気言語となっています。
> 
> 実は現在、人材市場ではApex開発者の争奪戦が繰り広げられており、歴3年もあればヘッドハントは当たり前。開発者からすると東京で1000万、大阪でも800万も狙える非常に魅力的なプログラミング言語となっています。

**Comment by kuratani** [comment]
質問箱に来た質問です！
* CTAになるといくらもえらるんですか？夢をください！
* テラスカイさんではどのような人が活躍できますか？
* ゴールデンフーディーでお馴染みの鈴木貞弘さんと震災の日に一緒だったそうですが、どうでしたか？
* 部下がコミュニティ活動することによってどのような利益を得られますか？
* 初めてpardotに携わるのですが、そもそもマーケティング知識がありません。何から始めればよいのでしょうか？
