### ISSUE TITLE
（宮脇さん）収録ネタ

### ISSUE THREAD

**Issue by kuratani** [migrationfm/migrationfm.github.io#8]
- 今年の目標・抱負
- 新しいオフィス
  - エンジニアの求める働き方
 - リモートワークの是非

- ISVあるある
  - ネイティブ、ハイブリッド、Webの住み分け

- その他
  - 銀河英雄伝説

**Comment by upwd-mywk** [comment]
・リモートワークの是非について
・ブラウザ対応
ネタがない
